export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING;';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const DELETE_PRODUCTS_PENDING = 'DELETE_PRODUCTS_PENDING;';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_ERROR = 'DELETE_PRODUCTS_ERROR';
